[2024-06-04T12:27:14.725+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: metrics_calculators2.pipelin_dsqe manual__2024-06-04T12:27:12.862412+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
