[2024-06-04T10:37:45.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T10:37:45.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_calculator.print_df manual__2024-06-04T10:32:42.476920+00:00 [queued]>
[2024-06-04T10:37:45.855+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_calculator.print_df manual__2024-06-04T10:32:42.476920+00:00 [queued]>
[2024-06-04T10:37:45.855+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-04T10:37:45.860+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): print_df> on 2024-06-04 10:32:42.476920+00:00
[2024-06-04T10:37:45.864+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10726) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T10:37:45.865+0000] {standard_task_runner.py:63} INFO - Started process 10728 to run task
[2024-06-04T10:37:45.865+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'metrics_calculator', 'print_df', 'manual__2024-06-04T10:32:42.476920+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_reader.py', '--cfg-path', '/tmp/tmpuih_c15p']
[2024-06-04T10:37:45.866+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask print_df
[2024-06-04T10:37:45.910+0000] {task_command.py:426} INFO - Running <TaskInstance: metrics_calculator.print_df manual__2024-06-04T10:32:42.476920+00:00 [running]> on host f291404afb14
[2024-06-04T10:37:45.959+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mehdizarria' AIRFLOW_CTX_DAG_ID='metrics_calculator' AIRFLOW_CTX_TASK_ID='print_df' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T10:32:42.476920+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T10:32:42.476920+00:00'
[2024-06-04T10:37:45.960+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T10:37:45.967+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T10:37:45.968+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_reader.py", line 22, in print_df
    lazy_df = ti.xcom_pull(task_ids='read_files')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3274, in xcom_pull
    return XCom.deserialize_value(first)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 705, in deserialize_value
    return BaseXCom._deserialize_value(result, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 700, in _deserialize_value
    return json.loads(result.value.decode("UTF-8"), cls=XComDecoder, object_hook=object_hook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 117, in object_hook
    return deserialize(dct)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 254, in deserialize
    raise ImportError(
ImportError: polars.lazyframe.frame.LazyFrame was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration
[2024-06-04T10:37:45.975+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=metrics_calculator, task_id=print_df, run_id=manual__2024-06-04T10:32:42.476920+00:00, execution_date=20240604T103242, start_date=20240604T103745, end_date=20240604T103745
[2024-06-04T10:37:45.979+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task print_df (polars.lazyframe.frame.LazyFrame was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration; 10728)
[2024-06-04T10:37:46.004+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-04T10:37:46.014+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T10:37:46.015+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
